" Generated by vim-plug
" Wed May 11 23:39:11 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['AutoSave.nvim'].commit = '3d342d6fcebeede15b6511b13a38a522c6f33bf8'
silent! let g:plugs['aerial.nvim'].commit = 'f1dfb0a05cd87f21175f33b3c8f4fbe4b1d77f18'
silent! let g:plugs['cmp-buffer'].commit = '12463cfcd9b14052f9effccbf1d84caa7a2d57f0'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'e6b5feb2e6560b61f31c756fb9231a0d7b10c73d'
silent! let g:plugs['cmp-path'].commit = '466b6b8270f7ba89abd59f402c73f63c7331ff6e'
silent! let g:plugs['editorconfig-vim'].commit = 'a8e3e66deefb6122f476c27cee505aaae93f7109'
silent! let g:plugs['gitsigns.nvim'].commit = 'aca84fd16ce129965d7c3c69de59f333d9da116c'
silent! let g:plugs['indent-blankline.nvim'].commit = '8567ac8ccd19ee41a6ec55bf044884799fa3f56b'
silent! let g:plugs['lualine.nvim'].commit = '619ededcff79e33a7e0ea677881dd07957449f9d'
silent! let g:plugs['nightfox.nvim'].commit = '63a8eb64e8559e4c910e91025a2959c4b50b8c54'
silent! let g:plugs['nvim-bqf'].commit = '3d174ca8198bafb3eb341001aafcf74ed4290d70'
silent! let g:plugs['nvim-cmp'].commit = 'a226b6a4ff72e5e809ed17734318233fb25c87f3'
silent! let g:plugs['nvim-dap'].commit = '2249fcfd09cdc27c08e9d2f3be5268ba81db3378'
silent! let g:plugs['nvim-lsp-installer'].commit = 'f5569f6785e675aaa01db9e44e0afcd065d6ba15'
silent! let g:plugs['nvim-lspconfig'].commit = 'ce8a4d88f0ed1eed43369e90e024a7599490342a'
silent! let g:plugs['nvim-tree.lua'].commit = '82ec79aac5557c05728d88195fb0d008cacbf565'
silent! let g:plugs['nvim-treesitter'].commit = '10d57b3ec14cac0b6b759e1eb5594617b8a7e883'
silent! let g:plugs['nvim-web-devicons'].commit = 'bdd43421437f2ef037e0dafeaaaa62b31d35ef2f'
silent! let g:plugs['plenary.nvim'].commit = '9069d14a120cadb4f6825f76821533f2babcab92'
silent! let g:plugs['telescope.nvim'].commit = '795a63ed293ba249a588e9e67aa1f2cec82028e8'

PlugUpdate!

