" Generated by vim-plug
" Fri 03 Dec 2021 04:21:41 PM PST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['auto-session'].commit = '1b4b4b7a993aae6d6281bc98194675b97ce9e962'
silent! let g:plugs['cmp-buffer'].commit = 'a706dc69c49110038fe570e5c9c33d6d4f67015b'
silent! let g:plugs['cmp-nvim-lsp'].commit = '134117299ff9e34adde30a735cd8ca9cf8f3db81'
silent! let g:plugs['cmp-path'].commit = 'd83839ae510d18530c6d36b662a9e806d4dceb73'
silent! let g:plugs['editorconfig-vim'].commit = '3078cd10b28904e57d878c0d0dab42aa0a9fdc89'
silent! let g:plugs['gitsigns.nvim'].commit = '119ebde2de917399aa89ad3664000a0e1750895a'
silent! let g:plugs['indent-blankline.nvim'].commit = '0f8df7e43f0cae4c44e0e8383436ad602f333419'
silent! let g:plugs['lualine.nvim'].commit = '1ae4f0aa74f0b34222c5ef3281b34602a76b2b00'
silent! let g:plugs['nvim-cmp'].commit = '10f5883c986967fa49b5219ece2404339dcfb84c'
silent! let g:plugs['nvim-dap'].commit = 'ce4e56f76598881d020e68037ae91310ea8b9d54'
silent! let g:plugs['nvim-lsp-installer'].commit = '4df84d7d3e8bcc9b98a1436b6b4155b3a727d41d'
silent! let g:plugs['nvim-lspconfig'].commit = '382712c4ecba5816f398379dd9d8c8200b025ca3'
silent! let g:plugs['nvim-tree.lua'].commit = 'e842f088847c98da59e14eb543bde11c45c87ef7'
silent! let g:plugs['nvim-treesitter'].commit = 'd6a0a26b8563409d4660def7320a4f4bc23954df'
silent! let g:plugs['nvim-web-devicons'].commit = '8df4988ecf8599fc1f8f387bbf2eae790e4c5ffb'
silent! let g:plugs['plenary.nvim'].commit = '1c31adb35fcebe921f65e5c6ff6d5481fa5fa5ac'
silent! let g:plugs['seoul256.vim'].commit = '57e545942fff2f796f26715bc0e937243dfa30c0'
silent! let g:plugs['session-lens'].commit = '4c1754bf5c2372d0a6265d40fb8f713bc27c8018'
silent! let g:plugs['telescope.nvim'].commit = '27294d73e4562cbc83c9c488b4618f012deade7e'
silent! let g:plugs['vscode-php-debug'].commit = 'f5c953405552845f02afb06fcf43da351b519260'

PlugUpdate!

