" Generated by vim-plug
" Thu Jan 13 22:55:58 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['DAPInstall.nvim'].commit = 'e15f8e37c3bf7c7d9902ac309fb5ef8dfa808a09'
silent! let g:plugs['cmp-buffer'].commit = 'f83773e2f433a923997c5faad7ea689ec24d1785'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'b4251f0fca1daeb6db5d60a23ca81507acf858c2'
silent! let g:plugs['cmp-path'].commit = '4d58224e315426e5ac4c5b218ca86cab85f80c79'
silent! let g:plugs['editorconfig-vim'].commit = '3078cd10b28904e57d878c0d0dab42aa0a9fdc89'
silent! let g:plugs['gitsigns.nvim'].commit = 'c18fc65c77abf95ac2e7783b9e7455a7a2fab26c'
silent! let g:plugs['indent-blankline.nvim'].commit = '0f8df7e43f0cae4c44e0e8383436ad602f333419'
silent! let g:plugs['lualine.nvim'].commit = 'bc5c2f5658821f98e55013eb3bec9d540c420470'
silent! let g:plugs['nightfox.nvim'].commit = '9c536aa95f80dd9f5eb08da8499fc5f6145407aa'
silent! let g:plugs['nvim-bqf'].commit = '5aca44fd316002e65ecd277d6a8a3120e2354a14'
silent! let g:plugs['nvim-cmp'].commit = '9f6d2b42253dda8db950ab38795978e5420a93aa'
silent! let g:plugs['nvim-dap'].commit = '3f1514d020f9d73a458ac04f42d27e5b284c0e48'
silent! let g:plugs['nvim-dap-ui'].commit = '12a7e0301332db0e005cb1ec1737f8a52530a8f5'
silent! let g:plugs['nvim-lsp-installer'].commit = '1caa06248102892ad11c2f91e6bf6bdd1f045b76'
silent! let g:plugs['nvim-lspconfig'].commit = 'd285f720ed2b26b687a06e9c7d5d41353dd2b743'
silent! let g:plugs['nvim-tree.lua'].commit = '0a2f6b0b6ba558a88c77a6b262af647760e6eca8'
silent! let g:plugs['nvim-treesitter'].commit = 'a76e1eb89d57e25cedbc71d6bf8e2d2c23d5d85b'
silent! let g:plugs['nvim-web-devicons'].commit = 'ac71ca88b1136e1ecb2aefef4948130f31aa40d1'
silent! let g:plugs['plenary.nvim'].commit = '563d9f6d083f0514548f2ac4ad1888326d0a1c66'
silent! let g:plugs['telescope.nvim'].commit = '5060f3f0ab33504e728a8673dc08679947c35ded'
silent! let g:plugs['vimwiki'].commit = '619f04f89861c58e5a6415a4f83847752928252d'

PlugUpdate!

